/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Aliza Nisar
 */
public class label extends javax.swing.JFrame {

    /**
     * Creates new form label
     */
    public label() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weight_kg = new javax.swing.JPanel();
        height_cm = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        heightfield = new javax.swing.JTextField();
        weightfield = new javax.swing.JTextField();
        bmi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        height_cm.setText("height in cm");

        calculate.setText("calculate");

        jLabel1.setText("weight in kg");

        heightfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightfieldActionPerformed(evt);
            }
        });

        weightfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightfieldActionPerformed(evt);
            }
        });

        bmi.setBackground(new java.awt.Color(0, 153, 255));
        bmi.setText("jLabel2");

        javax.swing.GroupLayout weight_kgLayout = new javax.swing.GroupLayout(weight_kg);
        weight_kg.setLayout(weight_kgLayout);
        weight_kgLayout.setHorizontalGroup(
            weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weight_kgLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(height_cm)
                    .addComponent(jLabel1)
                    .addComponent(calculate))
                .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(weight_kgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heightfield, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(weightfield))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(weight_kgLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bmi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 132, Short.MAX_VALUE))))
        );
        weight_kgLayout.setVerticalGroup(
            weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weight_kgLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height_cm)
                    .addComponent(heightfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(weightfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(weight_kgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(bmi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(weight_kg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(weight_kg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heightfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightfieldActionPerformed

    private void weightfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new label().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bmi;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel height_cm;
    private javax.swing.JTextField heightfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel weight_kg;
    private javax.swing.JTextField weightfield;
    // End of variables declaration//GEN-END:variables
}
